[YUNIKORN-569] Display pod namespace/name for the allocations on the apps/nodes page
apache/incubator-yunikorn-web pull request #54
Opened 2021-03-28 11:25 UTC by kobe860219

### What is this PR for?
Display pod namespace/name for the allocations on the apps/nodes page. Make application-key human readable.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-569

### How should this be tested?

### Screenshots (if appropriate)
<img width="1430" alt="截圖 2021-03-28 下午7 24 42" src="https://user-images.githubusercontent.com/48027290/112750454-46a95d80-8ffb-11eb-8704-a31a196c170c.png">
<img width="1434" alt="截圖 2021-03-28 下午7 24 30" src="https://user-images.githubusercontent.com/48027290/112750459-4c06a800-8ffb-11eb-88cc-eedb879e85ec.png">

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2021-03-29 01:10 UTC, wilfred-s commented
I think we need to look at the basic display of the data. Yes we need to make thing human readable but we also need to prevent displaying the same information over and over.
* An allocation displayed as part of a node does not need to show the nodeID or the partition. They cannot change for a node and I know which node I am looking at. That information is already there in the overview of the node.
* When looking at an app I see a similar issue. I do not need to see the appID, partition or the queue for the allocation information when I look at an app. That is always the same and should just be shown in the app overview.

Re-ordering of the data that is displayed, i.e. appID should be close the the key when looking at the node allocations. etc will also improve readability a lot.
Last point to make is that removing the key for allocations from the web UI will break any possibility to track that allocation in the logs. The key (ID) will be logged in the files so if you need to troubleshoot anything you need that and we cannot just remove it.

2021-03-31 15:00 UTC, kobe860219 commented
@yangwwei  @wilfred-s 
![image](https://user-images.githubusercontent.com/48027290/113165886-dc035680-9274-11eb-8a1f-7a8af801926f.png)

2021-03-31 22:30 UTC, yangwwei commented
@kobe860219  could u pls rebase because #51 just got merged. And pls fix the build issue https://travis-ci.com/github/apache/incubator-yunikorn-web/builds/221802141

2021-04-01 06:05 UTC, akhilpb001 commented
I agree with the improvements suggested by @wilfred-s. I feel that we can do both those improvements in one jira and no need for two jira.

@kobe860219  Could you pls fix the AllocationKey value "some-namespace/undefined"? If both namespace and podname are not available, pls fallback to display allocationId as we have had earlier.

2021-04-01 06:06 UTC, akhilpb001 requested changes
Added comments to fix.

2021-04-01 06:09 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +                console.log(alloc['displayName']);
remove console log

2021-04-01 06:09 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +                  alloc.allocationTags['kubernetes.io/meta/namespace'] +
use string literal format

2021-04-01 06:24 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +import { connectableObservableDescriptor } from 'rxjs/internal/observable/ConnectableObservable';
remove this if its not used.

2021-04-01 06:25 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +          data.forEach((app) => {
bracket for single param in arrow function is optional.

2021-04-01 06:26 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +          partitionName,
trailing comma is not needed, may be added by your editor.

2021-04-01 17:53 UTC, kobe860219 commented on src/app/services/scheduler/scheduler.service.ts
> +import { connectableObservableDescriptor } from 'rxjs/internal/observable/ConnectableObservable';
Removed

2021-04-01 17:53 UTC, kobe860219 commented on src/app/services/scheduler/scheduler.service.ts
> +                console.log(alloc['displayName']);
Removed

2021-04-01 18:20 UTC, kobe860219 commented
Fix  https://issues.apache.org/jira/browse/YUNIKORN-615 in this pr.

2021-04-08 15:49 UTC, akhilpb001 requested changes

2021-04-08 15:49 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +                  alloc['displayName'] = `some-namespace/undefined`;
@kobe860219 It does not make sense to display `some-namespace/undefined` when above specific allocationTags are not available. Could you pls change this to `n/a` may be?

2021-04-08 15:51 UTC, akhilpb001 commented on src/app/services/scheduler/scheduler.service.ts
> +                  alloc.allocationTags['kubernetes.io/meta/namespace'] &&
Change this if check to `alloc.allocationTags && alloc.allocationTags['kubernetes.io/meta/namespace'] && alloc.allocationTags['kubernetes.io/meta/podName']`

2021-04-08 15:53 UTC, akhilpb001 commented
Also pls attach latest screenshots with the fix.

2021-04-14 05:01 UTC, kobe860219 commented
@akhilpb001  Here is newest screenshots.
<img width="1440" alt="截圖 2021-04-14 下午12 59 31" src="https://user-images.githubusercontent.com/48027290/114656808-532ef500-9d21-11eb-90a0-07db5889aa89.png">
<img width="1440" alt="截圖 2021-04-14 下午12 59 42" src="https://user-images.githubusercontent.com/48027290/114656796-4f02d780-9d21-11eb-9d42-71567aaafcbc.png">

2021-04-19 06:44 UTC, akhilpb001 approved these changes

2021-04-19 06:44 UTC, merged